import type { Profile, Project, Contribution } from './types';

export const fallbackProfile: Profile = {
  id: '1',
  handle: 'nullopcode',
  name: 'nullopcode',
  title: 'Solana Builder & Protocol Engineer',
  bio: 'Building on-chain programs, DeFi infrastructure, and open-source tooling. Focused on Solana — staking systems, liquidity protocols, and cross-platform automation.',
  website: 'https://nullopcode.cv',
  solana_address: 'CGiuetrCxiaibJuxxCvrRjMyEjgmVEngxmvBXJtrmB5y',
  github_url: 'https://github.com/nullopcode',
  x_url: 'https://x.com/nullopcode',
  farcaster_url: 'https://warpcast.com/nullopcode',
  bluesky_url: 'https://bsky.app/profile/nullopcode.bsky.social',
  lens_url: 'https://hey.xyz/u/nullopcode',
  updated_at: new Date().toISOString(),
};

export const fallbackProjects: Project[] = [
  {
    id: '1',
    name: 'CLAWG Staking',
    slug: 'clawg-staking',
    description: 'Multi-tier token staking with time-weighted multipliers. 7 lock tiers (1d–365d), dual reward tokens (CLAWG + WSOL), on-chain distribution.',
    tech_stack: ['Rust', 'Anchor', 'Solana', 'TypeScript'],
    category: 'solana-program',
    status: 'active',
    program_id: 'Cbhx5F1fVJG83xkqse88rxatrj73UW9Lz9G7awBrW8WZ',
    chain: 'solana',
    sort_order: 0,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-12-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Mercenary Liquidity',
    slug: 'mercenary-liquidity',
    description: 'On-chain LP bounty protocol. Projects escrow SOL to incentivize liquidity providers with time-locked claims and automatic fee collection.',
    tech_stack: ['Rust', 'Anchor', 'Solana', 'TypeScript'],
    category: 'defi',
    status: 'active',
    program_id: '3hDJRcAJf5AHrRgkXhUUCcTYQVMkCubh9M6kTrsBZv55',
    chain: 'solana',
    sort_order: 1,
    created_at: '2024-10-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'CLAWG Fee Splitter',
    slug: 'clawg-fee-splitter',
    description: 'Automatic fee distribution program. Splits incoming SOL 30/70 between treasury and staking reward pools.',
    tech_stack: ['Rust', 'Anchor', 'Solana'],
    category: 'solana-program',
    status: 'shipped',
    program_id: '5QMXwAqPLVMzMdDAyT9QXJV2GZwxFDcvbz8u8dAe4sFT',
    chain: 'solana',
    sort_order: 2,
    created_at: '2024-07-01T00:00:00Z',
    updated_at: '2024-09-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'nullopcode-worker',
    slug: 'nullopcode-worker',
    description: 'Cloudflare Worker for cross-platform social posting. Farcaster, Bluesky, Lens v3 in parallel. GitHub push via Git Trees API.',
    tech_stack: ['TypeScript', 'Cloudflare Workers', 'Viem', 'AT Protocol'],
    category: 'worker',
    status: 'shipped',
    url: 'https://nullopcode-worker.nullopcode.workers.dev',
    chain: undefined,
    sort_order: 3,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'fixr.nexus',
    slug: 'fixr-nexus',
    description: 'Landing page and Token Hub with cross-chain staking UI. Base (EVM) and Solana staking in one interface.',
    tech_stack: ['Next.js', 'TypeScript', 'Wagmi', 'Solana Web3.js', 'Supabase'],
    category: 'frontend',
    status: 'active',
    url: 'https://fixr.nexus',
    chain: 'multi',
    sort_order: 4,
    created_at: '2024-08-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

export const fallbackContributions: Contribution[] = [
  {
    id: '1',
    repo_name: 'solana-labs/solana',
    repo_url: 'https://github.com/solana-labs/solana',
    description: 'Validator performance monitoring improvements',
    contribution_type: 'pr',
    merged: true,
    contributed_at: '2024-11-15',
    sort_order: 0,
    created_at: '2024-11-15T00:00:00Z',
  },
];
